import type { Metadata } from "next";
import { Archivo, Inter } from "next/font/google";
import "./globals.css";
import StayInTouch from "@/components/common/StayInTouch";
import Footer from "@/components/common/Footer";

const archivo = Archivo({
  subsets: ["latin"],
  variable: "--font-archivo",
  display: "swap",
  weight: ["400", "500", "600", "700", "900"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`space-y-2 lg:space-y-base p-micro lg:p-base bg-white ${archivo.variable} ${inter.variable} antialiased`}
      >
        {children}
        <StayInTouch />
        <Footer />
      </body>
    </html>
  );
}
